# Author: Richard Johansson

# group in file
group = "O3_O3"
description = "Default O3_O3 configuration"

# frequency related
f_start = 235176865000.0
#f_start = 236.7e9
f_end = 237676987100.0
# f_end = 236.2e9
f_res = 76300
f_clip = 100

# atmosphere and radiative transfer
target = "O3"
abs_species = ["O3", "H2O-PWR2022", "O2-PWR2022", "N2-SelfContStandardType"]
#abs_species = ["O3", "H2O-PWR2022", "O2-PWR2022"]
atmosphere_dim = 1
stokes_dim = 1
ppath_lmax = -1
iy_unit = "PlanckBT"
agendas = "default"

# loc
lat = 67.8
lon = 20.3

# OEM polyfit
poly_order = 1
poly_covs = [[0.5], [1.4]]

# OEM frequency shift
fshift_df = 7e3
fshift_cov = 10000

# OEM setup
f_interp_order = 1
stop_dx = 0.005
lm_ga_settings = [100, 2, 2, 1000, 5, 99]

# MORE OEM SETTINGS NEEDED!


