# Author: Richard Johansson

# group in file
group = "O3_O3"
description = "Default O3_O3 configuration"

# frequency related
f_start = 235176865000.0
f_end = 237676987100.0
f_res = 76300

# atmosphere and radiative transfer
abs_species = ["O3", "H2O-PWR2022", "O2-PWR2022", "O2-CIA-O2", "O2-CIA-N2", "N2-CIA-N2"]
atmosphere_dim = 1
stokes_dim = 1
ppath_lmax = -1
iy_unit = "RJBT"
agendas = "default"

# loc
lat = 67.8
lon = 20.3

# OEM polyfit
poly_order = 1
poly_covs = [[0.5], [1.4]]

# OEM frequency shift
fshift_df = 36e3
fshift_cov = 1000

# OEM setup
f_interp_order = 1
stop_dx = 0.01
lm_ga_settings = [10, 2, 2, 100, 1, 99]


